version: '3.8'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=secret
    depends_on:
      - rabbitmq
      - user-service
      - order-service
      - analytics-service

  user-service:
    build: ./user-service
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    ports:
      - "4000:4000"
    depends_on:
      - rabbitmq

  order-service:
    build: ./order-service
    environment:
      - KAFKA_BROKERS=kafka:29092
      - RABBITMQ_URL=amqp://rabbitmq
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - kafka

  analytics-service:
    build: ./analytics-service
    environment:
      - KAFKA_BROKERS=kafka:29092
    ports:
      - "6000:6000"
    depends_on:
      - kafka

  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    user: "0"   # Run as root
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    user: "0"   # Run as root
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

